### ISSUE TITLE
Crazy

### ISSUE THREAD

**Issue by hinell** [inkarkat/git-extensions#1]
This is insane amount of aliases out there in `gitconfig`. What's the purpose? Have you ever heard about zsh/bash completions before? This is crazy, mate! :zany_face:

**Comment by inkarkat** [comment]
Most of the aliases are variants that cover a particular range (to master, to the last checked-out branch, and so on). I've thought about creating them via a script, but there's enough irregularity that it wouldn't be easier to maintain, neither. I currently use Vim macros to make edits to all of them, so it's not as bad as it might seem.

Command-line completion could be used to expand a short alias into the full command, but that would just shift the complexity elsewhere, and I'd lose the short recognizable alias name in the command-line history, and also wouldn't be able to easily use the alias from within scripts.

I'm sharing this not with the intention of widespread use, but maybe someone finds a nice trick or inspiration for their own configuration (or is just stumped how far I've taken this - like you ;-) Cheers!

**Comment by inkarkat** [comment]
The amount of commands and branch-range variants has grown to a point where it's really tedious to make edits, preventing the addition of new variants (which should be easy).
Picking apart the historically grown aliases took a whole week (and I've found several bugs and gaps in (admittedly arcane and rarely used) combinations during that), but overall (with a few tactical enhancements), the 57 variants can be reduced to just 5 types (now in `lib/br-variants/*.sh`).

Maybe I should have made that switch earlier, but the sunken cost and huge discrepancy between just another complex edit (like dozens before) and the complete rewrite made that really hard.
